### ISSUE TITLE
font

### ISSUE THREAD

**Issue by incantatem1** [Elevict/Shade-Sanctuary#1]
the custom font doesn't load by default. installing it manually seems tedious since it's like.... 15 different fonts in the folder when i download it, that's so cluttered??? which one am i supposed to install exactly?

**Comment by Elevict** [comment]
Hey there, thanks for reaching out. The custom font does load by default. This is a new vault with and without the font.
![Recording 2024-08-07 at 10 15 31](https://github.com/user-attachments/assets/ed6f27e4-9543-4f5c-8b88-220042956245)

Perhaps there is something else that is causing a conflict with the font. Also, I am not sure what you mean by there being 15 different fonts in a folder. The Computer Modern font is in the theme.css file, and more specifically at the parts where it says @font-face. I'll be happy to help if you tell me the following so I can get to the bottom of this:

1. What snippets are you using?
2. Go to `Settings -> Appearance -> Font`. Have you currently set anything to be your interface, text, or monospace font? If so, you want to remove them since they override the Computer Modern font set by the theme.
3. Anything else that might influence how text looks such as some plugins.

Likewise, if you just only want the custom font without the entire theme I can make it into a snippet that you can enable and disable as well.

**Comment by incantatem1** [comment]
from what i'm seeing, 2. is the problem, i guess. i use a ton of themes and switch between them frequently, so i'd rather not change my editor font. but mostly, it bothers me that the font specifically doesn't load within callouts, which then not only not use my standard editor font, but actually times new roman, which looks pretty crappy. there are themes which override the standard editor font, maybe you can change the theme so it does that?

**Comment by Elevict** [comment]
Got it. I removed the "Times" font from callouts and defaulted it to "Computer Modern". I also added another setting where you can customize your fonts (Interface, Text, Codeblocks, and Callouts) using the style settings plugin. Hopefully this helps you out, and thanks for raising the issue.

![image](https://github.com/user-attachments/assets/2e52efa7-5285-4e50-9f67-8882b6a0e12b)

If there is anything else you would like, I'll be happy to add it in.

**Comment by incantatem1** [comment]
i uninstalled and reinstalled and now it works. it looks so much better now, thank you <3
